"use client"
import Footer from "@/components/footer"
import Nav from "@/components/nav"
// import './globals.css'

import { ChakraProvider } from "@chakra-ui/react"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Nav/>
        {children}
        <Footer/>
        </ChakraProvider>
        </body>
    </html>
  )
}
